"""empty message

Revision ID: 4c1ea08f91d1
Revises: 8ee86a888f97
Create Date: 2022-05-13 18:05:17.271488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1ea08f91d1'
down_revision = '8ee86a888f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'arches', 'maps', ['map_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arches', type_='foreignkey')
    # ### end Alembic commands ###
