"""empty message

Revision ID: cf3cc1a93e2c
Revises: 4c1ea08f91d1
Create Date: 2022-05-13 18:08:34.601248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3cc1a93e2c'
down_revision = '4c1ea08f91d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('arch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
