"""empty message

Revision ID: 99563d9f195e
Revises: 86b600f1db45
Create Date: 2022-05-13 18:18:03.906453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99563d9f195e'
down_revision = '86b600f1db45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bginfo',
    sa.Column('arch_id', sa.Integer(), nullable=False),
    sa.Column('bginfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.ForeignKeyConstraint(['bginfo_id'], ['background_info.id'], ),
    sa.PrimaryKeyConstraint('arch_id', 'bginfo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bginfo')
    # ### end Alembic commands ###
