"""empty message

Revision ID: 86b600f1db45
Revises: 8983cc9e0494
Create Date: 2022-05-13 18:14:33.933123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b600f1db45'
down_revision = '8983cc9e0494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('photographer', sa.String(length=128), nullable=True),
    sa.Column('link_to_db', sa.String(length=128), nullable=False),
    sa.Column('arch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_to_db')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    # ### end Alembic commands ###
