"""empty message

Revision ID: 8983cc9e0494
Revises: cf3cc1a93e2c
Create Date: 2022-05-13 18:10:16.077418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8983cc9e0494'
down_revision = 'cf3cc1a93e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_reporter', sa.String(length=128), nullable=True),
    sa.Column('references_sources', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('background_info')
    # ### end Alembic commands ###
