"""empty message

Revision ID: 87668a0563ff
Revises: 5caeb8d2f02d
Create Date: 2022-05-13 18:01:52.705553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87668a0563ff'
down_revision = '5caeb8d2f02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'arches', 'trails', ['trail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arches', type_='foreignkey')
    # ### end Alembic commands ###
