"""empty message

Revision ID: 56cec705b330
Revises: 99563d9f195e
Create Date: 2022-05-13 18:19:39.952196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cec705b330'
down_revision = '99563d9f195e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'arches', 'pictures', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arches', type_='foreignkey')
    # ### end Alembic commands ###
