"""empty message

Revision ID: 207eb1e7fcc4
Revises: 
Create Date: 2022-05-13 16:56:27.107637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207eb1e7fcc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gps_point_ew', sa.Numeric(), nullable=False),
    sa.Column('gps_point_ns', sa.Numeric(), nullable=False),
    sa.Column('size_gad', sa.Integer(), nullable=False),
    sa.Column('size_lad', sa.Numeric(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('picture_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arches')
    # ### end Alembic commands ###
