"""empty message

Revision ID: bba385137200
Revises: 56cec705b330
Create Date: 2022-05-13 18:20:26.394102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba385137200'
down_revision = '56cec705b330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trails', 'maps', ['map_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trails', type_='foreignkey')
    # ### end Alembic commands ###
