"""empty message

Revision ID: b8948a4c57e2
Revises: 8074f70898a9
Create Date: 2022-05-21 14:01:22.603172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8948a4c57e2'
down_revision = '8074f70898a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gps_point_ew', sa.Numeric(), nullable=False),
    sa.Column('gps_point_ns', sa.Numeric(), nullable=False),
    sa.Column('size_gad', sa.Integer(), nullable=False),
    sa.Column('size_lad', sa.Numeric(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Arches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Arches',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Arches_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('gps_point_ew', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('gps_point_ns', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('size_gad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size_lad', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('trail_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('map_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name='Arches_map_id_fkey'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], name='Arches_trail_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Arches_pkey'),
    sa.UniqueConstraint('name', name='Arches_name_key')
    )
    op.drop_table('arches')
    # ### end Alembic commands ###
