"""empty message

Revision ID: 8074f70898a9
Revises: a0c76c73d570
Create Date: 2022-05-21 13:58:56.625558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8074f70898a9'
down_revision = 'a0c76c73d570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Arches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gps_point_ew', sa.Numeric(), nullable=False),
    sa.Column('gps_point_ns', sa.Numeric(), nullable=False),
    sa.Column('size_gad', sa.Integer(), nullable=False),
    sa.Column('size_lad', sa.Numeric(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('trail_id', sa.Integer(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Arches')
    # ### end Alembic commands ###
