"""empty message

Revision ID: 4cb85acbed4c
Revises: 
Create Date: 2022-05-20 18:51:24.438652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb85acbed4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gps_point_ew', sa.Numeric(), nullable=False),
    sa.Column('gps_point_ns', sa.Numeric(), nullable=False),
    sa.Column('size_gad', sa.Integer(), nullable=False),
    sa.Column('size_lad', sa.Numeric(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arches')
    # ### end Alembic commands ###
