"""empty message

Revision ID: c125d68e08f7
Revises: 7907b7d3cb98
Create Date: 2022-05-20 19:02:59.076351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c125d68e08f7'
down_revision = '7907b7d3cb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arches', sa.Column('trail_id', sa.Integer(), nullable=True))
    op.add_column('arches', sa.Column('map_id', sa.Integer(), nullable=True))
    op.add_column('arches', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'arches', ['picture_id'])
    op.create_foreign_key(None, 'arches', 'maps', ['map_id'], ['id'])
    op.create_foreign_key(None, 'arches', 'trails', ['trail_id'], ['id'])
    op.create_foreign_key(None, 'arches', 'pictures', ['picture_id'], ['id'])
    op.add_column('trails', sa.Column('map_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'trails', 'maps', ['map_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trails', type_='foreignkey')
    op.drop_column('trails', 'map_id')
    op.drop_constraint(None, 'arches', type_='foreignkey')
    op.drop_constraint(None, 'arches', type_='foreignkey')
    op.drop_constraint(None, 'arches', type_='foreignkey')
    op.drop_constraint(None, 'arches', type_='unique')
    op.drop_column('arches', 'picture_id')
    op.drop_column('arches', 'map_id')
    op.drop_column('arches', 'trail_id')
    # ### end Alembic commands ###
