"""empty message

Revision ID: 7907b7d3cb98
Revises: 91ee46dda346
Create Date: 2022-05-20 19:01:51.511031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7907b7d3cb98'
down_revision = '91ee46dda346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('photographer', sa.String(length=128), nullable=True),
    sa.Column('link_to_db', sa.String(length=128), nullable=False),
    sa.Column('arch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_to_db')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    # ### end Alembic commands ###
