"""empty message

Revision ID: 9663e234bc72
Revises: b863bfe9eba5
Create Date: 2022-05-20 18:59:26.007424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9663e234bc72'
down_revision = 'b863bfe9eba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('arch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
