"""empty message

Revision ID: 2c191c05cb00
Revises: c125d68e08f7
Create Date: 2022-05-20 19:06:32.834373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c191c05cb00'
down_revision = 'c125d68e08f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arches_bginfo',
    sa.Column('arch_id', sa.Integer(), nullable=False),
    sa.Column('bginfo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.ForeignKeyConstraint(['bginfo_id'], ['background_info.id'], ),
    sa.PrimaryKeyConstraint('arch_id', 'bginfo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arches_bginfo')
    # ### end Alembic commands ###
