"""empty message

Revision ID: fd03693318ec
Revises: 
Create Date: 2022-05-21 16:00:10.837708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd03693318ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_infos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arches_background_infos',
    sa.Column('arch_id', sa.Integer(), nullable=True),
    sa.Column('background_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arch_id'], ['arches.id'], ),
    sa.ForeignKeyConstraint(['background_info_id'], ['background_infos.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arches_background_infos')
    op.drop_table('background_infos')
    op.drop_table('arches')
    # ### end Alembic commands ###
