"""empty message

Revision ID: e02af646d1b5
Revises: fd03693318ec
Create Date: 2022-05-21 16:04:59.161433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02af646d1b5'
down_revision = 'fd03693318ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arches', sa.Column('name', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'arches', ['name'])
    op.add_column('background_infos', sa.Column('original_reporter', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('background_infos', 'original_reporter')
    op.drop_constraint(None, 'arches', type_='unique')
    op.drop_column('arches', 'name')
    # ### end Alembic commands ###
