"""empty message

Revision ID: fcfb5c1b4d1a
Revises: e02af646d1b5
Create Date: 2022-05-21 16:07:39.450233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfb5c1b4d1a'
down_revision = 'e02af646d1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arches_background_infos', 'arch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('arches_background_infos', 'background_info_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arches_background_infos', 'background_info_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('arches_background_infos', 'arch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
